export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_ME = "SET_ME";
export const CLEAR_ME = "CLEAR_ME";

/////---------------- student types ---------------------/////

export const SET_TOTAL_COURSES = "SET_TOTAL_COURSES";
export const CLEAR_TOTAL_COURSES = "CLEAR_TOTAL_COURSES";

export const SET_COURSES_DETAILS = "SET_COURSES_DETAILS";
export const CLEAR_COURSES_DETAILS = "CLEAR_COURSES_DETAILS";

export const SET_TOTAL_REGISTERED_COURSES = "SET_TOTAL_REGISTERED_COURSES";
export const CLEAR_TOTAL_REGISTERED_COURSES = "CLEAR_TOTAL_REGISTERED_COURSES";

export const SET_MY_COURSES_LIST = "SET_MY_COURSES_LIST";
export const CLEAR_MY_COURSES_LIST = "CLEAR_MY_COURSES_LIST";

export const SET_TOTAL_EXAMS = "SET_TOTAL_EXAMS";
export const CLEAR_TOTAL_EXAMS = "CLEAR_TOTAL_EXAMS";

export const SET_EXAMS_DETAILS = "SET_EXAMS_DETAILS";
export const CLEAR_EXAMS_DETAILS = "CLEAR_EXAMS_DETAILS";

export const UPDATE_PROFILE_TEXT = "UPDATE_PROFILE_TEXT";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";

export const COURSE_REGISTER_STATUS_CODE = "COURSE_REGISTER_STATUS_CODE";
export const RESET_COURSE_REGISTER_STATUS_CODE = "RESET_COURSE_REGISTER_STATUS_CODE";

export const DOWNLOAD_PDF = "DOWNLOAD_PDF";
export const CLEAR_DOWNLOAD_PDF = "CLEAR_DOWNLOAD_PDF";

/////---------------- tutor types ---------------------/////

export const SET_TOTAL_STUDENTS_BY_COURSE = "SET_TOTAL_STUDENTS_BY_COURSE";
export const CLEAR_TOTAL_STUDENTS_BY_COURSE = "CLEAR_TOTAL_STUDENTS_BY_COURSE";

export const SET_MY_STUDENTS_LIST = "SET_MY_STUDENTS_LIST";
export const CLEAR_MY_STUDENTS_LIST = "CLEAR_MY_STUDENTS_LIST";

export const SET_EXAMS_RECORDS = "SET_EXAMS_RECORDS"
export const CLEAR_EXAMS_RECORDS = "CLEAR_EXAMS_RECORDS"

export const SET_TOTAL_STUDENTS_BY_EXAM = "SET_TOTAL_STUDENTS_BY_EXAM"
export const CLEAR_TOTAL_STUDENTS_BY_EXAM = "CLEAR_TOTAL_STUDENTS_BY_EXAM"

export const SET_EMAIL_SERVICE = "SET_EMAIL_SERVICE";
export const CLEAR_EMAIL_SERVICE = "CLEAR_EMAIL_SERVICE";

export const SET_GRADING_SERVICE = "SET_GRADING_SERVICE";
export const CLEAR_GRADING_SERVICE = "CLEAR_GRADING_SERVICE";

/////---------------- admin types ---------------------/////

export const SET_TOTAL_STUDENTS = "SET_TOTAL_STUDENTS"
export const CLEAR_TOTAL_STUDENTS = "CLEAR_TOTAL_STUDENTS"

export const SET_STUDENTS_DETAILS = "SET_STUDENTS_DETAILS"
export const CLEAR_STUDENTS_DETAILS = "CLEAR_STUDENTS_DETAILS"

export const SET_TOTAL_TUTORS = "SET_TOTAL_TUTORS"
export const CLEAR_TOTAL_TUTORS = "CLEAR_TOTAL_TUTORS"

export const SET_NEW_TUTOR = "SET_NEW_TUTOR"
export const CLEAR_NEW_TUTOR = "CLEAR_NEW_TUTOR"

export const SET_TUTORS_DETAILS = "SET_TUTORS_DETAILS"
export const CLEAR_TUTORS_DETAILS = "CLEAR_TUTORS_DETAILS"

export const SET_NEW_STUDENT = "SET_NEW_STUDENT"
export const CLEAR_NEW_STUDENT = "CLEAR_NEW_STUDENT"

export const SET_NEW_COURSE = "SET_NEW_COURSE"
export const CLEAR_NEW_COURSE = "CLEAR_NEW_COURSE"

export const SET_DEPARTMENTS_DETAILS = "SET_DEPARTMENTS_DETAILS"
export const CLEAR_DEPARTMENTS_DETAILS = "CLEAR_DEPARTMENTS_DETAILS"

export const SET_TUTORS = "SET_TUTORS"
export const CLEAR_TUTORS = "CLEAR_TUTORS"